import { Spark } from '@editor/Editor/Property/cells';
import { colorSpark } from '@editor/Editor/Property/spark/common/colorSpark';
import headerGroup from './common/headerGroup';
import texture2D from './common/texture2D';
import tilingOffset from './common/tilingOffset';

export const PBRMaterial = {
  spark: 'grid',
  content: [
    headerGroup,
    {
      spark: 'group',
      label: '材质设置',
      content: {
        spark: 'grid',
        content: [
          {
            spark: 'select',
            index: 'blendMode',
            label: '混合模式',
            tooltip: '混合模式',
            options: [
              {
                label: '不透明',
                value: 0,
              },
              {
                label: '遮罩',
                value: 1,
              },
              {
                label: '透明',
                value: 2,
              },
              {
                label: '默认',
                value: 3,
              },
            ],
            defaultValue: 0,
          },
          {
            spark: 'check',
            index: 'blendMode',
            check: {
              hidden: (mode: number) => mode === 0,
            },
            content: {
              spark: 'number',
              index: 'alpha',
              label: '不透明度',
              tooltip: '不透明度',
              precision: 3,
              step: 0.03,
              min: 0,
              max: 1,
              defaultValue: 1,
            },
          },
          {
            spark: 'check',
            index: 'blendMode',
            check: {
              hidden: (mode: number) => mode !== 1,
            },
            content: {
              spark: 'number',
              index: 'alphaTestValue',
              label: 'Alpha 裁剪',
              tooltip: 'Alpha 裁剪',
              precision: 3,
              step: 0.03,
              min: 0,
              max: 1,
              defaultValue: 0.5,
            },
          },
          colorSpark({
            spark: 'color',
            index: 'baseColor',
            label: '颜色',
            defaultValue: [1, 1, 1],
          }),
          texture2D('baseColorTextureUrl', '颜色贴图'),
          {
            spark: 'number',
            index: 'metallic',
            label: '金属度',
            tooltip: '金属度',
            precision: 3,
            step: 0.03,
            min: 0,
            max: 1,
            defaultValue: 1,
          },
          {
            spark: 'number',
            index: 'roughness',
            label: '粗糙度',
            tooltip: '粗糙度',
            precision: 3,
            step: 0.03,
            min: 0,
            max: 1,
            defaultValue: 1,
          },
          texture2D('metallicRoughnessTextureUrl', '金属粗糙度贴图'),
          texture2D('normalTextureUrl', '法线贴图'),
          {
            spark: 'check',
            index: 'normalTextureUrl',
            check: {
              hidden: (url: string) => url,
            },
            content: {
              spark: 'number',
              index: 'normalTextureScale',
              label: '法线缩放',
              tooltip: '法线缩放',
              precision: 3,
              step: 0.03,
              min: 0,
              max: 1,
              defaultValue: 0.5,
            },
          },
          colorSpark({
            spark: 'color',
            index: 'emissiveColor',
            label: '自发光颜色',
            defaultValue: [1, 1, 1],
          }),
          texture2D('emissiveTextureUrl', '自发光贴图'),
          {
            spark: 'number',
            index: 'emissiveIntensity',
            label: '自发光强度',
            tooltip: '自发光强度',
            precision: 3,
            step: 0.03,
            min: 0,
            defaultValue: 1,
          },
          {
            spark: 'check',
            index: 'blendMode',
            check: {
              hidden: (mode: number) => mode === 0,
            },
            content: texture2D('opacityTextureUrl', '不透明度贴图'),
          },
          texture2D('occlusionTextureUrl', '遮蔽贴图'),
          {
            spark: 'check',
            index: 'occlusionTextureUrl',
            check: {
              hidden: (url: string) => url,
            },
            content: {
              spark: 'number',
              index: 'occlusionTextureIntensity',
              label: '遮蔽贴图强度',
              tooltip: '遮蔽贴图强度',
              precision: 3,
              step: 0.03,
              min: 0,
              max: 1,
              defaultValue: 1,
            },
          },
          tilingOffset,
          {
            spark: 'number',
            index: 'ior',
            label: '折射率',
            tooltip: '折射率',
            precision: 3,
            step: 0.03,
            min: 1,
            max: 3,
            defaultValue: 1.5,
          },
          {
            spark: 'boolean',
            index: 'doubleSided',
            label: '双面渲染',
            default: false,
          },
        ],
      },
    },
    {
      spark: 'group',
      label: '清漆',
      content: {
        spark: 'grid',
        content: [
          {
            spark: 'number',
            index: 'clearCoat',
            label: '强度',
            tooltip: '强度',
            precision: 3,
            step: 0.03,
            min: 0,
            max: 1,
            defaultValue: 1,
          },
          texture2D('clearCoatTextureUrl', '贴图'),
          {
            spark: 'number',
            index: 'clearCoatRoughness',
            label: '粗糙度',
            tooltip: '粗糙度',
            precision: 3,
            step: 0.03,
            min: 0,
            max: 1,
            defaultValue: 1,
          },
          texture2D('clearCoatRoughnessTextureUrl', '粗糙度贴图'),
          texture2D('clearCoatNormalTextureUrl', '法线贴图'),
          {
            spark: 'number',
            index: 'clearCoatlor',
            label: '折射率',
            tooltip: '折射率',
            precision: 3,
            step: 0.03,
            min: 1,
            max: 3,
            defaultValue: 1.5,
          },
        ],
      },
    },
    {
      spark: 'group',
      label: '光泽',
      content: {
        spark: 'grid',
        content: [
          {
            spark: 'number',
            index: 'sheen',
            label: '强度',
            tooltip: '强度',
            precision: 3,
            step: 0.03,
            min: 0,
            max: 1,
            defaultValue: 1,
          },
          colorSpark({
            spark: 'color',
            index: 'sheenColor',
            label: '颜色',
            defaultValue: [0, 0, 0],
          }),
          texture2D('sheenColorTextureUrl', '颜色贴图'),
          {
            spark: 'number',
            index: 'sheenRoughness',
            label: '粗糙度',
            tooltip: '粗糙度',
            precision: 3,
            step: 0.03,
            min: 0,
            max: 1,
            defaultValue: 1,
          },
          texture2D('sheenRoughnessTextureUrl', '粗糙度贴图'),
        ],
      },
    },
    {
      spark: 'group',
      label: '投射',
      content: {
        spark: 'grid',
        content: [
          {
            spark: 'number',
            index: 'transmission',
            label: '强度',
            tooltip: '强度',
            precision: 3,
            step: 0.03,
            min: 0,
            max: 1,
            defaultValue: 1,
          },
          texture2D('transmissionTextureUrl', '贴图'),
        ],
      },
    },
  ],
} as Spark;
