import { SCENE_FIXTURE_VERSION } from '@editor/Editor/Header/hooks/compatibles/version';
// import alphaMask from './playableIcons/alpha_mask.png';
import cover from './playable_cover.png';

// console.log('alphaMask', alphaMask);

export default (id: number, width: number, height: number) => ({
  name: '加载场景',
  id,
  sceneId: 916,
  orderId: 1,
  type: 'Scene',
  editor: {
    selected: {},
    scale: 50,
    count: 140,
    moment: 0,
    playable: true,
    loading: true,
    capture: cover,
    dataVersion: SCENE_FIXTURE_VERSION,
  },
  props: {
    [id]: { type: 'Scene', name: '加载场景', width, height, x: 0, y: 0 },
    '1654484707107': {
      x: 0,
      y: 0,
      width: 750,
      height: 1334,
      rotation: 0,
      anchorX: 0.5,
      anchorY: 0.5,
      fillType: 0,
      scaleX: 1,
      scaleY: 1,
      alpha: 1,
      enabled: true,
      color: 'black',
      top: true,
      bottom: true,
      center: true,
      name: '蒙层',
      url: 'https://lf6-cdn2-tos.bytegoofy.com/byte-creativelab/platform/fe/images/26aa440110c228290ce5.png',
      _editor: {
        name: 'mask',
        originWidth: 311,
        originHeight: 555,
      },
      type: 'Sprite',
    },
    '1654484707108': {
      x: 0,
      y: 1066,
      width: 750,
      height: 34,
      rotation: 0,
      anchorX: 0.5,
      anchorY: 0.5,
      scaleX: 1,
      scaleY: 1,
      alpha: 1,
      enabled: true,
      name: '主标题文案',
      text: '加载页的主标题',
      fontSize: 34,
      layoutByPercent: true,
      color: 'rgba(255,255,255,1)',
      align: 'center',
      valign: 'middle',
      top: true,
      bottom: true,
      center: true,
      wordWrap: true,
      bold: true,
      italic: false,
      type: 'Text',
    },
    '1654484707109': {
      x: 0,
      y: 1122,
      width: 750,
      height: 29,
      rotation: 0,
      anchorX: 0.5,
      anchorY: 0.5,
      scaleX: 1,
      scaleY: 1,
      alpha: 1,
      enabled: true,
      layoutByPercent: true,
      name: '副标题文案',
      text: '加载页的副标题',
      fontSize: 29,
      color: 'rgba(255,255,255,1)',
      align: 'center',
      valign: 'middle',
      wordWrap: true,
      bold: true,
      italic: false,
      type: 'Text',
      top: true,
      bottom: true,
      center: true,
    },
    '1656473199114': {
      x: 195,
      y: 706,
      width: 360,
      height: 360,
      rotation: 0,
      anchorX: 0.5,
      anchorY: 0.5,
      scaleX: 1,
      scaleY: 1,
      top: true,
      bottom: true,
      center: true,
      alpha: 1,
      enabled: true,
      layoutByPercent: true,
      name: '试玩图标',
      url: 'material/private/preview/4b3f06ff990f5b0e0ff59f4030bf74a1/sequence.json',
      _editor: {
        name: '试玩图标',
        originWidth: 360,
        originHeight: 360,
        cover:
          'https://creativelab-proxy.bytedance.com/api/upload/bucket/files/images/d9b574d367be6f84456c002938cd3866.png',
      },
      type: 'FrameAnime',
    },
    '1656473199115': {
      script: 'Controller',
      name: '试玩图标',
      time: 0,
      duration: 1100,
      loop: true,
      type: 'Controller',
    },
  },
  nodes: [
    {
      id: 1654484707107,
      type: 'Sprite',
      editor: {
        isLocked: true,
        isHidden: false,
      },
      name: '蒙层',
      enabled: true,
      scripts: [],
      nodes: [],
    },
    {
      id: 1654484707108,
      type: 'Text',
      editor: {
        isLocked: true,
        isHidden: false,
      },
      name: '主标题文案',
      enabled: true,
      scripts: [],
      nodes: [],
    },
    {
      id: 1654484707109,
      type: 'Text',
      editor: {
        isLocked: true,
        isHidden: false,
      },
      name: '副标题文案',
      enabled: true,
      scripts: [],
      nodes: [],
    },
    {
      id: 1656473199114,
      type: 'FrameAnime',
      editor: {
        isLocked: true,
        isHidden: false,
        animations: [['试玩图标', 1100]],
      },
      name: '试玩图标',
      enabled: true,
      scripts: [
        {
          id: 1656473199115,
          type: 'Controller',
          name: '试玩图标',
          time: 0,
          duration: 1100,
          loop: true,
          script: 'Controller',
        },
      ],
      nodes: [],
    },
  ],
  history: {
    undoStack: [],
    redoStack: [],
  },
});
