export const keywordMap = {
  Sun: '太阳',
  Earth: '地球',
  Moon: '月球',
  Sky: '天空',
  Tree: '树',
  River: '河流',
  Mountain: '山脉',
  Ocean: '海洋',
  Beach: '海滩',
  Forest: '森林',
  Flower: '花',
  Grass: '草',
  Rock: '岩石',
  Lake: '湖泊',
  Rain: '雨',
  Snow: '雪',
  Cloud: '云',
  Storm: '暴风雨',
  Thunder: '雷声',
  Lightning: '闪电',
  Volcano: '火山',
  Waterfall: '瀑布',
  Stream: '小溪',
  Valley: '山谷',
  Desert: '沙漠',
  Iceberg: '冰山',
  Aurora: '极光',
  Rainbow: '彩虹',
  Fog: '雾',
  Sunlight: '阳光',
  Raindrop: '雨滴',
  Dew: '露珠',
  Hail: '冰雹',
  Snowflake: '雪花',
  Mist: '薄雾',
  Breeze: '微风',
  Wind: '风',
  Hurricane: '飓风',
  Typhoon: '台风',
  Tornado: '龙卷风',
  Earthquake: '地震',
  Tsunami: '海啸',
  Flood: '洪水',
  Wildfire: '野火',
  Blizzard: '暴风雪',
  Landslide: '山崩',
  'Tree trunk': '树干',
  'Tree bark': '树皮',
  'Tree leaves': '树叶',
  'Tree branch': '树枝',
  'Tree root': '树根',
  'Flower petal': '花瓣',
  'Flower stem': '花茎',
  'Flower bud': '花蕾',
  'Grass blade': '草刺',
  'Grass seed': '草种',
  'Mountain peak': '山峰',
  'Mountain range': '山脉',
  'Mountain trail': '山径',
  'Ocean wave': '海浪',
  'Ocean current': '海流',
  'Ocean tide': '潮汐',
  'Ocean depth': '海洋深度',
  'Beach sand': '沙滩',
  'Beach shell': '海贝壳',
  'Beach rock': '海岸岩石',
  'Forest canopy': '森林冠层',
  'Forest floor': '森林地面',
  'Forest animals': '森林动物',
};

export const keywordMap2 = {
  'game art': '游戏艺术',
  'oil painting': '油画',
  'fantasy vivid colors': '色彩动人',
  photorealistic: '照片',
};
