import { css } from 'emotion';

export default {
  container: css({
    flex: 'auto',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '30px 0',
  }),
  items: css({
    flex: 1,
    display: 'flex',
    flexWrap: 'wrap',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
    width: 1156,
  }),
  empty: css({
    height: '100%',
    margin: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  }),
  loadbox: css({
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    background: 'rgba(255, 255, 255, 0.3)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  }),
  textarea: css({
    maxHeight: '34px',
    width: '100%',
    color: '#333333',
    marginTop: '0',
    resize: 'none',
  }),
  changeTags: css({
    width: '500px',
    height: '300px',
    display: 'flex',
    border: '1px solid #e8e8e8',
    position: 'absolute',
    top: '35px',
    zIndex: 11,
  }),
  tagList: css({
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    overflow: 'auto',
    alignContent: 'flex-start',
  }),
  clear: css({
    position: 'absolute',
    right: '50px',
    top: '25%',
  }),
  categories: css({
    margin: '10px',
    padding: '3px',
    borderRadius: '2px',
    position: 'relative',
  }),
  catTags: css({
    width: '280px',
    border: '1px solid #e8e8e8',
    position: 'absolute',
    left: 0,
    top: '38px',
    zIndex: 11,
    display: ' flex',
    flexWrap: 'wrap',
  }),
};
