const theme = {
  base: 'vs-dark' as const,
  inherit: true,
  rules: [
    { token: '', background: '272822' },
    { token: 'comment', foreground: '75715e' },
    { token: 'string', foreground: 'e6db74' },
    { token: 'constant.numeric', foreground: 'ae81ff' },
    { token: 'constant.language', foreground: 'ae81ff' },
    { token: 'constant.character', foreground: 'ae81ff' },
    { token: 'constant.other', foreground: 'ae81ff' },
    { token: 'keyword', foreground: 'f92672' },
    { token: 'storage', foreground: 'f92672' },
    { token: 'storage.type', foreground: '66d9ef', fontStyle: 'italic' },
    { token: 'entity.name.class', foreground: 'a6e22e', fontStyle: 'underline' },
    { token: 'entity.other.inherited-class', foreground: 'a6e22e', fontStyle: 'italic underline' },
    { token: 'entity.name.function', foreground: 'a6e22e' },
    { token: 'variable.parameter', foreground: 'fd971f', fontStyle: 'italic' },
    { token: 'entity.name.tag', foreground: 'f92672' },
    { token: 'entity.other.attribute-name', foreground: 'a6e22e' },
    { token: 'support.function', foreground: '66d9ef' },
    { token: 'support.constant', foreground: '66d9ef' },
    { token: 'support.type', foreground: '66d9ef', fontStyle: 'italic' },
    { token: 'support.class', foreground: '66d9ef', fontStyle: 'italic' },
    { token: 'invalid', foreground: 'f8f8f0', background: 'f92672' },
    { token: 'invalid.deprecated', foreground: 'f8f8f0', background: 'ae81ff' },
    { token: 'meta.structure.dictionary.json string.quoted.double.json', foreground: 'cfcfc2' },
    { token: 'meta.diff', foreground: '75715e' },
    { token: 'meta.diff.header', foreground: '75715e' },
    { token: 'markup.deleted', foreground: 'f92672' },
    { token: 'markup.inserted', foreground: 'a6e22e' },
    { token: 'markup.changed', foreground: 'e6db74' },
    { token: 'constant.numeric.line-number.find-in-files - match', foreground: 'ae81ffa0' },
    { token: 'entity.name.filename.find-in-files', foreground: 'e6db74' },
  ],
  colors: {
    'editor.foreground': '#F8F8F2',
    'editor.background': '#272822',
    'editor.selectionBackground': '#49483E',
    'editor.lineHighlightBackground': '#3E3D32',
    'editorCursor.foreground': '#F8F8F0',
    'editorWhitespace.foreground': '#3B3A32',
    'editorIndentGuide.activeBackground': '#9D550FB0',
    'editor.selectionHighlightBorder': '#222218',
  },
};

export default theme;
